const API_URL='https://script.google.com/macros/s/AKfycbwaG2eWIgappSD0RH8e_utJYZohc8hZOOBLIuxwdh5Q8jZm4TNI-daFDybuGOxbH_25/exec';let token=localStorage.getItem('fc5token')||'';let state={players:[],pending:[],matches:[],config:{name:'FC Championship 5.0',phase:'FASE DE GRUPOS'}};
const $=id=>document.getElementById(id); async function api(action,data={}){if(API_URL.startsWith('COLE_')) throw Error('Configure a URL do Apps Script em app.js');let r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token,...data})});let j=await r.json();if(!j.ok)throw Error(j.error||'Erro');return j}
function render(){let p=state.players,m=state.matches;$('nPlayers').textContent=p.length;$('nMatches').textContent=m.length;$('nPending').textContent=state.pending.length;$('phase').textContent=state.config.phase;document.title=state.config.name;renderTables();$('players').innerHTML=p.map(x=>`<div class="card player"><b>${esc(x.name)}</b><small>${esc(x.nick)} • ${esc(x.platform)} • Grupo ${x.group}</small></div>`).join('')||'<p>Nenhum jogador aprovado.</p>';renderBracket();if(!document.getElementById('panel').hidden)renderAdmin()}
function renderTables(){let tabs=['A','B','C','D'];$('tabs').innerHTML=tabs.map((g,i)=>`<button class="${i===0?'active':''}" onclick="showGroup('${g}',this)">Grupo ${g}</button>`).join('');showGroup('A',$('tabs').firstElementChild)}
function showGroup(g,btn){document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');let rows=state.players.filter(p=>p.group===g).map(p=>{let a=state.matches.filter(x=>x.p1===p.id||x.p2===p.id),v=0,e=0,d=0,gp=0,gc=0;a.forEach(x=>{let me=x.p1===p.id?x.s1:x.s2,op=x.p1===p.id?x.s2:x.s1;gp+=me;gc+=op;if(me>op)v++;else if(me===op)e++;else d++});return{p,v,e,d,gp,gc,sg:gp-gc,pts:v*3+e}}).sort((a,b)=>b.pts-a.pts||b.sg-a.sg||b.gp-a.gp);$('tables').innerHTML=`<div class="tableWrap"><table class="table"><thead><tr><th>#</th><th>Jogador</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>PTS</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.p.name)}</td><td>${r.v+r.e+r.d}</td><td>${r.v}</td><td>${r.e}</td><td>${r.d}</td><td>${r.sg}</td><td><b>${r.pts}</b></td></tr>`).join('')}</tbody></table></div>`}
function renderBracket(){$('bracket').innerHTML='<div class="round"><h3>Quartas</h3>'+['Jogo 1','Jogo 2','Jogo 3','Jogo 4'].map(x=>`<div class="match">${x}<br><small>A definir</small></div>`).join('')+'</div><div class="round"><h3>Semifinais</h3><div class="match">Semi 1<br><small>A definir</small></div><div class="match">Semi 2<br><small>A definir</small></div></div><div class="round"><h3>Final</h3><div class="match">🏆 Final<br><small>A definir</small></div></div>'}
function renderAdmin(){ $('summary').innerHTML=`<b>${state.players.length}</b> jogadores aprovados<br><b>${state.pending.length}</b> inscrições pendentes<br><b>${state.matches.length}</b> partidas`; $('cfgName').value=state.config.name;$('cfgPhase').value=state.config.phase;$('pending').innerHTML=state.pending.length?state.pending.map(p=>`<div class="pendingItem"><span>${esc(p.name)}<br><small>${esc(p.nick)} • ${esc(p.platform)}</small></span><span><button class="btn small" onclick="approve('${p.id}')">Aprovar</button> <button class="btn small" onclick="reject('${p.id}')">Recusar</button></span></div>`).join(''):'<p>Nenhuma pendência.</p>';let opts=state.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('p1').innerHTML=opts;$('p2').innerHTML=opts;$('results').innerHTML=state.matches.slice().reverse().map(x=>`<div class="resultItem"><span>${esc(x.n1)} <b>${x.s1} × ${x.s2}</b> ${esc(x.n2)}</span><button class="btn small" onclick="delMatch('${x.id}')">Excluir</button></div>`).join('')||'<p>Nenhum resultado.</p>'}
async function load(){try{let j=await api('publicData');state=j.data;render()}catch(e){$('signupMsg').textContent=e.message}}
$('signup').onsubmit=async e=>{e.preventDefault();try{await api('register',{player:{name:$('name').value,nick:$('nick').value,whatsapp:$('whatsapp').value,platform:$('platform').value,team:$('team').value}});$('signup').reset();$('signupMsg').textContent='Inscrição enviada! Aguarde a aprovação.';await load()}catch(x){$('signupMsg').textContent=x.message}};
$('loginBtn').onclick=async()=>{try{let j=await api('login',{password:$('pass').value});token=j.token;localStorage.setItem('fc5token',token);$('login').hidden=true;$('panel').hidden=false;state=j.data;render()}catch(e){$('loginMsg').textContent=e.message}};
$('logout').onclick=()=>{localStorage.removeItem('fc5token');token='';$('login').hidden=false;$('panel').hidden=true};$('saveCfg').onclick=async()=>{try{let j=await api('saveConfig',{config:{name:$('cfgName').value,phase:$('cfgPhase').value}});state=j.data;render()}catch(e){alert(e.message)}};$('result').onsubmit=async e=>{e.preventDefault();try{let j=await api('addMatch',{p1:$('p1').value,p2:$('p2').value,s1:+$('s1').value,s2:+$('s2').value});state=j.data;render()}catch(x){alert(x.message)}};
async function approve(id){try{let j=await api('approve',{id});state=j.data;render()}catch(e){alert(e.message)}}async function reject(id){try{let j=await api('reject',{id});state=j.data;render()}catch(e){alert(e.message)}}async function delMatch(id){try{let j=await api('deleteMatch',{id});state=j.data;render()}catch(e){alert(e.message)}}function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}$('menu').onclick=()=>document.querySelector('nav').classList.toggle('open');load();setInterval(load,30000);
