const ADMIN_PASSWORD='fifadoscrente';
function setup(){const ss=SpreadsheetApp.getActive();const sheets=['Config','Players','Matches'];const heads={Config:['key','value'],Players:['id','name','nick','whatsapp','platform','team','group','status','createdAt'],Matches:['id','p1','n1','s1','p2','n2','s2','createdAt']};sheets.forEach((n,i)=>{let sh=ss.getSheetByName(n)||ss.insertSheet(n);if(sh.getLastRow()===0)sh.appendRow(heads[n])});let cfg=ss.getSheetByName('Config');if(cfg.getLastRow()===1)cfg.getRange(2,1,2,2).setValues([['name','FC Championship 5.0'],['phase','FASE DE GRUPOS']]);return 'OK'}
function doGet(){return ContentService.createTextOutput(JSON.stringify({ok:true,service:'crente Championship API'})).setMimeType(ContentService.MimeType.JSON)}
function doPost(e){try{setup();const q=JSON.parse(e.postData.contents||'{}');const action=q.action;let out;switch(action){case'publicData':out=publicData();break;case'login':out=login(q.password);break;case'register':out=register(q.player);break;case'approve':out=admin(q,'approve');break;case'reject':out=admin(q,'reject');break;case'addMatch':out=admin(q,'addMatch');break;case'deleteMatch':out=admin(q,'deleteMatch');break;case'saveConfig':out=admin(q,'saveConfig');break;default:throw Error('Ação inválida')}return json({ok:true,data:out.data||out,token:out.token})}catch(err){return json({ok:false,error:err.message})}}
function json(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function publicData(){const ss=SpreadsheetApp.getActive();const cfg=rows('Config'), ps=rows('Players'), ms=rows('Matches');const config={name:(cfg.find(x=>x[0]=='name')||['','FC Championship 5.0'])[1],phase:(cfg.find(x=>x[0]=='phase')||['','FASE DE GRUPOS'])[1]};const players=ps.filter(x=>x[7]=='approved').map(x=>({id:x[0],name:x[1],nick:x[2],whatsapp:x[3],platform:x[4],team:x[5],group:x[6]}));const pending=ps.filter(x=>x[7]=='pending').map(x=>({id:x[0],name:x[1],nick:x[2],whatsapp:x[3],platform:x[4],team:x[5],group:x[6]}));const matches=ms.map(x=>({id:x[0],p1:x[1],n1:x[2],s1:+x[3],p2:x[4],n2:x[5],s2:+x[6]}));return{config,players,pending,matches}}
function login(pw){if(pw!==ADMIN_PASSWORD)throw Error('Senha incorreta');const token=Utilities.getUuid();CacheService.getScriptCache().put('admin_'+token,'1',21600);return{token,data:publicData()}}
function auth(q){if(!q.token||CacheService.getScriptCache().get('admin_'+q.token)!=='1')throw Error('Sessão expirada. Entre novamente.')}
function register(p){if(!p||!p.name||!p.nick)throw Error('Preencha nome e Nick/ID');const sh=SpreadsheetApp.getActive().getSheetByName('Players');const id=Utilities.getUuid();const groups=['A','B','C','D'];const count=sh.getLastRow();const g=groups[Math.floor(Math.random()*4)];sh.appendRow([id,p.name,p.nick,p.whatsapp||'',p.platform||'PS5',p.team||'',g,'pending',new Date().toISOString()]);return publicData()}
function admin(q,a){auth(q);const ss=SpreadsheetApp.getActive();if(a==='approve'||a==='reject'){const sh=ss.getSheetByName('Players');const vals=sh.getDataRange().getValues();const r=vals.findIndex(x=>x[0]===q.id);if(r<1)throw Error('Jogador não encontrado');sh.getRange(r+1,8).setValue(a==='approve'?'approved':'rejected');return{data:publicData()}}if(a==='addMatch'){if(q.p1===q.p2)throw Error('Escolha jogadores diferentes');const ps=publicData().players;const p1=ps.find(x=>x.id===q.p1),p2=ps.find(x=>x.id===q.p2);if(!p1||!p2)throw Error('Jogador não encontrado');SpreadsheetApp.getActive().getSheetByName('Matches').appendRow([Utilities.getUuid(),p1.id,p1.name,Number(q.s1),p2.id,p2.name,Number(q.s2),new Date().toISOString()]);return{data:publicData()}}if(a==='deleteMatch'){const sh=ss.getSheetByName('Matches'),v=sh.getDataRange().getValues(),r=v.findIndex(x=>x[0]===q.id);if(r<1)throw Error('Resultado não encontrado');sh.deleteRow(r+1);return{data:publicData()}}if(a==='saveConfig'){const sh=ss.getSheetByName('Config');['name','phase'].forEach((k,i)=>{const v=sh.getDataRange().getValues(),r=v.findIndex(x=>x[0]===k);if(r>=1)sh.getRange(r+1,2).setValue(q.config[k])});return{data:publicData()}}}
function rows(sheet){return SpreadsheetApp.getActive().getSheetByName(sheet).getDataRange().getValues().slice(1)}
